name: ci

on: push

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
            - name: Install dependencies
              run: npm ci
                
    build:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: npm run build
    lint:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Lint
              run: npm run lint

    check-format:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Check format
              run: npm run check-format